// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa1iU4cAHSyHtl9umfL-YPV0PtUdfyCv4',
    appId: '1:181783457456:web:8e0b57b2f4d183a7d4d575',
    messagingSenderId: '181783457456',
    projectId: 'segarku-27cf6',
    authDomain: 'segarku-27cf6.firebaseapp.com',
    databaseURL: 'https://segarku-27cf6-default-rtdb.firebaseio.com',
    storageBucket: 'segarku-27cf6.firebasestorage.app',
    measurementId: 'G-EWS4PNEJK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMKnw4jGmXNCuCgH0zbIaWlKxszJp3SXk',
    appId: '1:181783457456:android:bfa4029ca5a6d7b7d4d575',
    messagingSenderId: '181783457456',
    projectId: 'segarku-27cf6',
    databaseURL: 'https://segarku-27cf6-default-rtdb.firebaseio.com',
    storageBucket: 'segarku-27cf6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa1iU4cAHSyHtl9umfL-YPV0PtUdfyCv4',
    appId: '1:181783457456:web:d180982f76a017a0d4d575',
    messagingSenderId: '181783457456',
    projectId: 'segarku-27cf6',
    authDomain: 'segarku-27cf6.firebaseapp.com',
    databaseURL: 'https://segarku-27cf6-default-rtdb.firebaseio.com',
    storageBucket: 'segarku-27cf6.firebasestorage.app',
    measurementId: 'G-KJ88N5D6FL',
  );
}
